In [1]:
# Loading the Libraries
from dotenv import load_dotenv
load_dotenv()
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import os,glob

In [2]:
INCOME_GROUP_PATH = '/Users/boristsao/Documents/Projects/canada-vis/data-exploration/final-data/total_income_groups_in_2020_for_the_population_aged_15_years_and_over_in_private_households.csv'
income_group = pd.read_csv(INCOME_GROUP_PATH)

/var/folders/0p/c1842hdx3cl1f16fhby8ffhr0000gn/T/ipykernel_27481/3202496802.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  income_group = pd.read_csv(INCOME_GROUP_PATH)

In [3]:
new_columns = {}
for column in income_group.columns:
    new_columns[column] = column.lower().replace("$", "").replace(",", "").replace("_(including_loss)", "")
income_group = income_group.rename(columns=new_columns)
income_group.head()

,census_year,dguid,alt_geo_code,geo_level,geo_name,total_10000_to_19999,total_100000_to_149999,total_150000_and_over,total_20000_to_29999,total_30000_to_39999,...,female_20000_to_29999,female_30000_to_39999,female_40000_to_49999,female_50000_to_59999,female_60000_to_69999,female_70000_to_79999,female_80000_to_89999,female_90000_to_99999,female_under_10000,female_without_total_income
0,2021,2021A000210,10,Province,Newfoundland and Labrador,58585.0,24300.0,11800.0,76150.0,60370.0,...,42985.0,33000.0,25675.0,17240.0,11165.0,7655.0,6025.0,5705.0,19740.0,7160.0
1,2021,2021A000211,11,Province,Prince Edward Island,14340.0,4860.0,2095.0,20890.0,19790.0,...,11845.0,10545.0,8660.0,6495.0,3995.0,2590.0,2100.0,1590.0,4925.0,2015.0
2,2021,2021A000212,12,Province,Nova Scotia,102030.0,40070.0,16510.0,140270.0,111240.0,...,79660.0,61425.0,51940.0,35745.0,23050.0,16435.0,13755.0,10175.0,36980.0,13935.0
3,2021,2021A000213,13,Province,New Brunswick,79855.0,26865.0,10835.0,111820.0,95545.0,...,63140.0,51060.0,43955.0,27910.0,17445.0,12260.0,10500.0,6565.0,28055.0,10585.0
4,2021,2021A000224,24,Province,Quebec,809375.0,385890.0,170890.0,1124265.0,896520.0,...,624485.0,482445.0,437325.0,341305.0,231415.0,158980.0,125930.0,85780.0,258155.0,92310.0

In [4]:
income_group = income_group.drop(columns=['census_year', 'alt_geo_code', 'geo_level', 'geo_name', 'total_10000_to_19999', 'total_100000_to_149999', 'total_150000_and_over', 'total_20000_to_29999', 'total_30000_to_39999', 'total_40000_to_49999', 'total_50000_to_59999', 'total_60000_to_69999', 'total_70000_to_79999', 'total_80000_to_89999', 'total_90000_to_99999','total_under_10000', 'total_without_total_income' ])
for column in income_group.columns:
    print(column)

dguid
male_10000_to_19999
male_100000_to_149999
male_150000_and_over
male_20000_to_29999
male_30000_to_39999
male_40000_to_49999
male_50000_to_59999
male_60000_to_69999
male_70000_to_79999
male_80000_to_89999
male_90000_to_99999
male_under_10000
male_without_total_income
female_10000_to_19999
female_100000_to_149999
female_150000_and_over
female_20000_to_29999
female_30000_to_39999
female_40000_to_49999
female_50000_to_59999
female_60000_to_69999
female_70000_to_79999
female_80000_to_89999
female_90000_to_99999
female_under_10000
female_without_total_income

In [5]:
# Local Connection
ssl_args = {'ssl_ca': "/etc/ssl/cert.pem"}

conn_string = 'mysql+pymysql://' + "root" + ':' + "Chuckie2020!" + '@' + "localhost" + '/' + "canada_vis" 

engine = create_engine(conn_string, connect_args=ssl_args)

In [6]:
with engine.begin() as connection:
    income_group.to_sql('income_groups', con=connection, if_exists='replace')

In [7]:
 # Connecting to Planet Scale
ssl_args = {'ssl_ca': "/etc/ssl/cert.pem"}

conn_string = 'mysql+pymysql://' + os.getenv("USERNAME") + ':' + os.getenv("PASSWORD") + '@' + os.getenv("HOST") + '/' + os.getenv("DATABASE") 

engine = create_engine(conn_string, connect_args=ssl_args)

with engine.begin() as connection:
    income_group.to_sql('income_groups', con=connection, if_exists='replace')