In [8]:
# Loading the Libraries
from dotenv import load_dotenv
load_dotenv()
import os
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import os,glob

In [2]:
# Change the column names
csv = '/Users/boristsao/Documents/Projects/canada-vis/data-exploration/final-data/age_groups_of_the_population.csv'
df = pd.read_csv(csv, encoding="ISO-8859-1",low_memory=False)

In [10]:
data_path = '/Users/boristsao/Documents/Projects/canada-vis/data-exploration/final-data/'
for csv_file in glob.glob(os.path.join(data_path, '*.csv')):
    df = pd.read_csv(csv_file, encoding="ISO-8859-1",low_memory=False)
    new_columns = {}

    for column in df.columns:
        new_columns[column] = column.lower().replace(" ", "_")

    new_df = df.rename(columns = new_columns)
    new_df = new_df.fillna(0)
    new_df.to_csv(csv_file)

In [3]:
new_columns = {}

for column in df.columns:
    new_columns[column] = column.lower().replace(" ", "_")

new_df = df.rename(columns = new_columns)
new_df = new_df.fillna(0)
new_df.head()

,census_year,alt_geo_code,geo_level,geo_name,total_0_to_4_years,total_10_to_14_years,total_100_years_and_over,total_15_to_19_years,total_20_to_24_years,total_25_to_29_years,...,female_50_to_54_years,female_55_to_59_years,female_60_to_64_years,female_65_to_69_years,female_70_to_74_years,female_75_to_79_years,female_80_to_84_years,female_85_to_89_years,female_90_to_94_years,female_95_to_99_years
0,2021,10,Province,Newfoundland and Labrador,18985.0,26175.0,80.0,25720.0,26075.0,25045.0,...,19685.0,21615.0,21830.0,20735.0,17805.0,11780.0,7280.0,3910.0,1880.0,485.0
1,2021,11,Province,Prince Edward Island,6750.0,8800.0,35.0,8560.0,10570.0,9200.0,...,5115.0,6005.0,5970.0,5450.0,4770.0,3095.0,2110.0,1355.0,640.0,210.0
2,2021,12,Province,Nova Scotia,40340.0,49300.0,290.0,48180.0,58005.0,60430.0,...,33175.0,39870.0,39850.0,35665.0,31140.0,20925.0,14040.0,8740.0,4300.0,1435.0
3,2021,13,Province,New Brunswick,32280.0,40605.0,250.0,39090.0,42125.0,42380.0,...,26450.0,31795.0,31870.0,29605.0,25135.0,16580.0,11310.0,7120.0,3645.0,1200.0
4,2021,24,Province,Quebec,422980.0,489425.0,1975.0,429400.0,460660.0,527150.0,...,260325.0,308465.0,317900.0,277950.0,237910.0,177050.0,119580.0,81150.0,44535.0,11790.0

In [4]:
new_df.describe

<bound method NDFrame.describe of        census_year  alt_geo_code           geo_level  \
0             2021            10            Province
1             2021            11            Province
2             2021            12            Province
3             2021            13            Province
4             2021            24            Province
...            ...           ...                 ...
63402         2021      62080024  Dissemination area
63403         2021      62080025  Dissemination area
63404         2021      62080026  Dissemination area
63405         2021      62080027  Dissemination area
63406         2021      62080028  Dissemination area

                        geo_name  total_0_to_4_years  total_10_to_14_years  \
0      Newfoundland and Labrador             18985.0               26175.0
1           Prince Edward Island              6750.0                8800.0
2                    Nova Scotia             40340.0               49300.0
3                  New Brunswick             32280.0               40605.0
4                         Quebec            422980.0              489425.0
...                          ...                 ...                   ...
63402                   62080024                25.0                  25.0
63403                   62080025                50.0                  50.0
63404                   62080026               100.0                 100.0
63405                   62080027               115.0                  90.0
63406                   62080028                75.0                  55.0

       total_100_years_and_over  total_15_to_19_years  total_20_to_24_years  \
0                          80.0               25720.0               26075.0
1                          35.0                8560.0               10570.0
2                         290.0               48180.0               58005.0
3                         250.0               39090.0               42125.0
4                        1975.0              429400.0              460660.0
...                         ...                   ...                   ...
63402                       0.0                  35.0                  35.0
63403                       0.0                  55.0                  30.0
63404                       0.0                  75.0                  50.0
63405                       0.0                  65.0                  60.0
63406                       0.0                  40.0                  45.0

       total_25_to_29_years  ...  female_50_to_54_years  \
0                   25045.0  ...                19685.0
1                    9200.0  ...                 5115.0
2                   60430.0  ...                33175.0
3                   42380.0  ...                26450.0
4                  527150.0  ...               260325.0
...                     ...  ...                    ...
63402                  30.0  ...                   20.0
63403                  30.0  ...                   10.0
63404                  60.0  ...                   20.0
63405                  65.0  ...                   15.0
63406                  50.0  ...                   20.0

       female_55_to_59_years  female_60_to_64_years  female_65_to_69_years  \
0                    21615.0                21830.0                20735.0
1                     6005.0                 5970.0                 5450.0
2                    39870.0                39850.0                35665.0
3                    31795.0                31870.0                29605.0
4                   308465.0               317900.0               277950.0
...                      ...                    ...                    ...
63402                   20.0                   10.0                   10.0
63403                   15.0                   15.0                    0.0
63404                   25.0                    5.0                   10.0
63405                   10.0                   10.0                    0.0
63406                    5.0                   10.0                    5.0

       female_70_to_74_years  female_75_to_79_years  female_80_to_84_years  \
0                    17805.0                11780.0                 7280.0
1                     4770.0                 3095.0                 2110.0
2                    31140.0                20925.0                14040.0
3                    25135.0                16580.0                11310.0
4                   237910.0               177050.0               119580.0
...                      ...                    ...                    ...
63402                    5.0                    0.0                    0.0
63403                    5.0                    0.0                    0.0
63404                   10.0                    0.0                    5.0
63405                    5.0                    0.0                    0.0
63406                    0.0                    5.0                    0.0

       female_85_to_89_years  female_90_to_94_years  female_95_to_99_years
0                     3910.0                 1880.0                  485.0
1                     1355.0                  640.0                  210.0
2                     8740.0                 4300.0                 1435.0
3                     7120.0                 3645.0                 1200.0
4                    81150.0                44535.0                11790.0
...                      ...                    ...                    ...
63402                    0.0                    0.0                    0.0
63403                    0.0                    0.0                    0.0
63404                    0.0                    0.0                    0.0
63405                    0.0                    0.0                    0.0
63406                    0.0                    0.0                    0.0

[63407 rows x 67 columns]>

In [5]:
ssl_args = {'ssl_ca': "/etc/ssl/cert.pem"}

conn_string = 'mysql+pymysql://' + os.getenv("USERNAME") + ':' + os.getenv("PASSWORD") + '@' + os.getenv("HOST") + '/' + os.getenv("DATABASE") 

engine = create_engine(conn_string, connect_args=ssl_args)
with engine.begin() as connection:
    new_df.to_sql('age_groups', con=connection, if_exists='append')

In [6]:
with engine.begin() as connection:
    read_test = pd.read_sql("SELECT * FROM age_groups WHERE GEO_NAME='British Columbia'", con=connection)
#     df = pd.read_csv(csv,encoding="ISO-8859-1")
#     df.to_sql('age_groups', con=connection, if_exists='append')
read_test.head()

,index,census_year,alt_geo_code,geo_level,geo_name,total_0_to_4_years,total_10_to_14_years,total_100_years_and_over,total_15_to_19_years,total_20_to_24_years,...,female_50_to_54_years,female_55_to_59_years,female_60_to_64_years,female_65_to_69_years,female_70_to_74_years,female_75_to_79_years,female_80_to_84_years,female_85_to_89_years,female_90_to_94_years,female_95_to_99_years
0,9,2021,59,Province,British Columbia,216825.0,255790.0,1515.0,253690.0,294650.0,...,170460.0,183825.0,184920.0,166700.0,141995.0,95015.0,65780.0,42005.0,23120.0,6925.0